services:
  aituconnectapi:
    image: ${DOCKER_REGISTRY-}aituconnectapi
    build:
      context: .
      dockerfile: AituConnectApi/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - redis

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    depends_on:
        - rabbitmq

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: horizaV123++
      POSTGRES_DB: AituConnectApp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
    pgdata: 
    rabbitmqdata:
    redisdata: